### ISSUE TITLE
boost-system missing

### ISSUE THREAD

**Issue by dschwen** [idaholab/conda-moose#39]
when installing only up to moose-petsc configuring libmesh/metaphysicl fails with a missing `boost/system/error_code.hpp` message.

**Comment by dschwen** [comment]
`conda install boost` fixes this (should be installed automatically as a dependency)

**Comment by milljm** [comment]
@dschwen 
I might be inclined to put this in moose-tools. But I don't think it belongs in moose-petsc. PETSc does not _depend_ on Boost. libMesh does. So I can see the reason for adding boost to moose-libmesh (which I will do, as it currently is not in there...). 

I am not sure where to place this dependency for a developer. You, being a developer knew to `conda install boost`. A normal user will not be installing _only_ moose-petsc. I suppose it wouldn't hurt to place the dependency in moose-petsc...

**Comment by aeslaughter** [comment]
The boost system is not missing, when we get the basic stack working as is we will add that ability to optionally add boost and rely on conda to do the correct thing.

`conda install moose-libmesh` will use a libmesh without boost

`conda install moose-libmesh boost` will use a libmesh with boost

This is the most flexible way to do this stuff and it is supported by conda, the VTK package does this with OSMESA.

**Comment by milljm** [comment]
Leaving open, until we figure out how to do what Andrew mentioned.

**Comment by milljm** [comment]
@dschwen
and @aeslaughter cause maybe you have an idea.

I am not sure this is possible. And I am pretty frustrated over it. Bad on Conda if I am actually right about this.

It would appear, that in order to make use of 'features', one needs some measure of control over recipe of the feature your trying to track (meaning I need to alter conda-forge's boost package). I know this sounds crazy. The Boost recipe needs the 'track_feature' added to it:

```yaml
package:
  name: boost
  version: 1.0
build:
  track_feature: <----  Add these two lines to boost recipe so 
    - boost      <----/ other recipes can... track it? That doesn't sound right.
```
Sure enough: [features](https://docs.conda.io/projects/conda-build/en/stable/concepts/features.html)

Example:
[VTK](https://github.com/conda-forge/vtk-feedstock/blob/f3f4058c0c2ef3b9f92a877978c52dfe6696c7f6/recipe/meta.yaml#L24) is creating a 'feature'. Which, if the user also installs libmesa, VTK specifically _built_ with mesa will be installed instead. But first, [libmesa](https://github.com/conda-forge/mesalib-feedstock/blob/a1dd66d8af73ced8106796636d0873ba482d80fc/recipe/meta.yaml#L29) must add the track_feature ...TO ITSELF...?.

WHY this is necessary, I have no idea. As far as I can tell, it's harmless to have 'track_feature' enabled in a recipe. It's like you have to opt-in your recipe to allow it to be tracked or something.

**Comment by milljm** [comment]
I will gladly re-open this, if/when someone/me figures this out.

**Comment by milljm** [comment]
I've posted my question about this with conda-forge: https://groups.google.com/forum/#!topic/conda-forge/MZtoCXkstOQ
